definitions:
  app.Pager:
    properties:
      page:
        type: integer
      page_size:
        type: integer
      total_rows:
        type: integer
    type: object
  errorcode.Error:
    properties:
      code:
        type: integer
      details:
        items:
          type: string
        type: array
      msg:
        type: string
    type: object
  model.Tag:
    properties:
      content:
        description: 暫存欄位
      created_by:
        type: string
      created_on:
        type: integer
      deleted_on:
        type: integer
      id:
        type: integer
      is_del:
        type: integer
      modified_by:
        type: string
      modified_on:
        type: integer
      name:
        description: 標籤名稱
        type: string
      state:
        description: 狀態 0:關閉 1:開啟
        type: integer
    type: object
  model.TagSwagger:
    properties:
      list:
        items:
          $ref: '#/definitions/model.Tag'
        type: array
      pager:
        $ref: '#/definitions/app.Pager'
    type: object
  service.CreateArticleRequest:
    properties:
      author:
        type: string
      category:
        description: 文章分類
        type: string
      content:
        description: 文章內容
        type: string
      publish_date:
        description: 文章作者
        type: string
      state:
        description: 文章狀態
        type: integer
      tags:
        description: 文章標籤
        items:
          type: string
        type: array
      title:
        description: 文章標題
        type: string
    required:
    - author
    - category
    - content
    - publish_date
    - tags
    - title
    type: object
info:
  contact: {}
  description: 部落格建立
  termsOfService: https://github.com/go-programing-tour-book
  title: 部落格系統
  version: "1.0"
paths:
  /api/v1/articles:
    post:
      consumes:
      - application/json
      parameters:
      - description: 文章資料
        in: body
        name: createArticleRequest
        required: true
        schema:
          $ref: '#/definitions/service.CreateArticleRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/model.TagSwagger'
        "400":
          description: 請求錯誤
          schema:
            $ref: '#/definitions/errorcode.Error'
        "500":
          description: 內部錯誤
          schema:
            $ref: '#/definitions/errorcode.Error'
      summary: 新增文章
  /api/v1/tags:
    get:
      parameters:
      - description: 標籤名稱
        in: query
        maxLength: 100
        name: name
        type: string
      - default: 1
        description: 狀態
        enum:
        - 0
        - 1
        in: query
        name: state
        type: integer
      - description: 頁碼
        in: query
        name: page
        type: integer
      - description: 每頁數量
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/model.TagSwagger'
        "400":
          description: 請求錯誤
          schema:
            $ref: '#/definitions/errorcode.Error'
        "500":
          description: 內部錯誤
          schema:
            $ref: '#/definitions/errorcode.Error'
      summary: 取得多個標籤
    post:
      parameters:
      - description: 標籤名稱
        in: query
        maxLength: 100
        name: name
        required: true
        type: string
      - default: 1
        description: 狀態
        enum:
        - 0
        - 1
        in: query
        name: state
        type: integer
      - description: 建立者
        in: query
        maxLength: 100
        name: created_by
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/model.TagSwagger'
        "400":
          description: 請求錯誤
          schema:
            $ref: '#/definitions/errorcode.Error'
        "500":
          description: 內部錯誤
          schema:
            $ref: '#/definitions/errorcode.Error'
      summary: 新增標籤
  /api/v1/tags/{id}:
    delete:
      parameters:
      - description: 標籤ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/model.TagSwagger'
        "400":
          description: 請求錯誤
          schema:
            $ref: '#/definitions/errorcode.Error'
        "500":
          description: 內部錯誤
          schema:
            $ref: '#/definitions/errorcode.Error'
      summary: 刪除標籤
    put:
      parameters:
      - description: 標籤ID
        in: path
        name: id
        required: true
        type: integer
      - description: 標籤名稱
        in: body
        maxLength: 100
        name: name
        schema:
          type: string
      - default: 1
        description: 狀態
        enum:
        - 0
        - 1
        in: body
        name: state
        schema:
          type: integer
      - description: 修改者
        in: body
        maxLength: 100
        name: modified_by
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/model.TagSwagger'
        "400":
          description: 請求錯誤
          schema:
            $ref: '#/definitions/errorcode.Error'
        "500":
          description: 內部錯誤
          schema:
            $ref: '#/definitions/errorcode.Error'
      summary: 更新標籤
swagger: "2.0"
